"""Data Analysis Notebook

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cRlck9bHcLWpHJNXcyrPETZr4Z5KfCSK

##Air Quality
"""

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv('air_quality_Nov2017.csv')
df['Generated Date Time'] = pd.to_datetime(df['Generated'])
df['Year'] = df['Generated Date Time'].dt.year
air_quality_mapping = {"Good": 1, "Moderate": 2}
df['Air Quality'] = df['Air Quality'].map(air_quality_mapping)
average_air_quality = df.groupby('Year')['Air Quality'].mean().reset_index()
print(average_air_quality)



"""##Bus Stops"""

# Load your CSV data into a Pandas DataFrame
# Replace 'your_file.csv' with the actual filename
df = pd.read_csv('bus_stops.csv')

# Create a new column 'Day Bus Stops' with 0 as the initial value
df['Day Bus Stops'] = 0

# Create a new column 'Night Bus Stops' with 0 as the initial value
df['Night Bus Stops'] = 0

# Update the 'Day Bus Stops' column based on the 'Transport' column
df.loc[df['Transport'] == 'Day bus stop', 'Day Bus Stops'] = 1

# Update the 'Night Bus Stops' column based on the 'Transport' column
df.loc[df['Transport'] == 'Night bus stop', 'Night Bus Stops'] = 1

# Group by 'District.Name' and sum the 'Day Bus Stops' and 'Night Bus Stops'
result = df.groupby('District.Name')[['Day Bus Stops', 'Night Bus Stops']].sum().reset_index()

# Print the resulting DataFrame
print(result)

import pandas as pd
import matplotlib.pyplot as plt

# Load your CSV data into a Pandas DataFrame
# Replace 'your_file.csv' with the actual filename
df = pd.read_csv('bus_stops.csv')

# Create a new column 'Day Bus Stops' with 0 as the initial value
df['Day Bus Stops'] = 0

# Create a new column 'Night Bus Stops' with 0 as the initial value
df['Night Bus Stops'] = 0

# Update the 'Day Bus Stops' column based on the 'Transport' column
df.loc[df['Transport'] == 'Day bus stop', 'Day Bus Stops'] = 1

# Update the 'Night Bus Stops' column based on the 'Transport' column
df.loc[df['Transport'] == 'Night bus stop', 'Night Bus Stops'] = 1

# Group by 'District.Name' and sum the 'Day Bus Stops' and 'Night Bus Stops'
result = df.groupby('District.Name')[['Day Bus Stops', 'Night Bus Stops']].sum().reset_index()

# Plot the data
plt.figure(figsize=(12, 6))
plt.bar(result['District.Name'], result['Day Bus Stops'], label='Day Bus Stops')
plt.bar(result['District.Name'], result['Night Bus Stops'], label='Night Bus Stops', bottom=result['Day Bus Stops'])
plt.xlabel('District Name')
plt.ylabel('Number of Bus Stops')
plt.title('Number of Day and Night Bus Stops per District')
plt.xticks(rotation=45, ha='right')
plt.legend()
plt.tight_layout()
plt.show()

"""##Immigrants by Nationality"""

import pandas as pd
import matplotlib.pyplot as plt

# Read the CSV file into a Pandas DataFrame
df = pd.read_csv('immigrants_by_nationality.csv')

# Exclude the rows where Nationality is 'Spain'
df_filtered = df[df['Nationality'] != 'Spain']

# Group the data by nationality and sum the number of immigrants over the years
nationality_counts = df_filtered.groupby('Nationality')['Number'].sum()

# Sort the nationalities by the total number of immigrants in descending order
top_nationalities = nationality_counts.sort_values(ascending=False).head(20)

# Create a bar plot
plt.figure(figsize=(12, 6))
top_nationalities.plot(kind='bar')
plt.xlabel('Nationality')
plt.ylabel('Total Number of Immigrants')
plt.title('Top 20 Immigrant Nationalities (Excluding Spain) Over the Years')
plt.xticks(rotation=90)
plt.show()

df = pd.read_csv('immigrants_by_nationality.csv')

# Group the data by 'Year', 'District Name', and 'Nationality', and sum the 'Number' column
result = df.groupby(['Year', 'District Name', 'Nationality'])['Number'].sum().reset_index()
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
# Print the resulting DataFrame
print(result['Nationality'].unique())

