"""Data Analysis Notebook

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cRlck9bHcLWpHJNXcyrPETZr4Z5KfCSK

##Air Quality
"""

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv('air_quality_Nov2017.csv')
df['Generated Date Time'] = pd.to_datetime(df['Generated'])
df['Year'] = df['Generated Date Time'].dt.year
air_quality_mapping = {"Good": 1, "Moderate": 2}
df['Air Quality'] = df['Air Quality'].map(air_quality_mapping)
average_air_quality = df.groupby('Year')['Air Quality'].mean().reset_index()
print(average_air_quality)
